name: NSE File Downloader

on:
  workflow_dispatch: # Allows you to manually click "Run workflow"

permissions:
  contents: write # Allows GitHub to save the downloaded file back to your repo

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download NSE File
        run: |
          # Uses a User-Agent header to prevent NSE from blocking the request
          curl -sL -H "User-Agent: Mozilla/5.0" \
            "https://archives.nseindia.com/archives/equities/mto/MTO_04092026.DAT" \
            -o "reports/MTO_28082026.DAT"
            "https://archives.nseindia.com/archives/equities/mto/MTO_04092026.DAT" \
            -o "reports/MTO_03092026.DAT"
            "https://archives.nseindia.com/archives/equities/mto/MTO_04092026.DAT" \
            -o "reports/MTO_02092026.DAT"
            "https://archives.nseindia.com/archives/equities/mto/MTO_04092026.DAT" \
            -o "reports/MTO_01092026.DAT"
            "https://archives.nseindia.com/archives/equities/mto/MTO_04092026.DAT" \
            -o "reports/MTO_31082026.DAT"

      - name: Commit and Push to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add reports/MTO_04092026.DAT
          
          # Only commits if the file is new or updated
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add NSE MTO report" && git push)
